[package]
name = "wfc"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "wfc"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30.0"
image = "0.24.6"
imageproc = "0.23.0"
rand = "0.8.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"